version: "3.3"
services:
  app:
    container_name: node-log-transmitter
    restart: always
    build: .
    environment:
      PORT: 8080
      LOG_GENERATOR_INTERVAL: 3000
    ports:
      - "8080:8080"
